# Generated by Django 2.2.1 on 2020-05-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mail', models.CharField(max_length=300)),
                ('sender_address', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.CharField(max_length=1000000)),
                ('app_open_time', models.CharField(max_length=300)),
                ('mail_open_time', models.CharField(max_length=300)),
                ('isreplied_count', models.IntegerField()),
                ('first_reply_time', models.IntegerField()),
                ('body_spams_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='senders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('sender_reply_count', models.IntegerField()),
                ('sender_importance', models.FloatField()),
            ],
        ),
    ]
