# Generated by Django 2.2.1 on 2020-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='type_of',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
