# Generated by Django 2.2.1 on 2020-05-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_email_type_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body_spams_score',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='email',
            name='first_reply_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='isreplied_count',
            field=models.IntegerField(default=None),
        ),
    ]
