# Generated by Django 2.2.1 on 2020-05-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200520_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body_spams_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='email',
            name='isreplied_count',
            field=models.IntegerField(default=0),
        ),
    ]
