# Generated by Django 2.2.1 on 2020-05-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200520_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='received_time',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
