# Generated by Django 2.2.1 on 2020-05-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_email_received_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='completeflag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='sender_name',
            field=models.CharField(default="/", max_length=300),
        ),
        migrations.AddField(
            model_name='senders',
            name='sender_delete_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='senders',
            name='sender_total_mails',
            field=models.IntegerField(default=0),
        ),
    ]
