# Generated by Django 2.2.1 on 2020-05-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200526_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sender_name',
            field=models.CharField(default='sender', max_length=300),
        ),
    ]
