# Generated by Django 2.2.1 on 2020-05-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200526_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='senders',
            name='sender_opened_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='senders',
            name='sender_total_count',
            field=models.IntegerField(default=0),
        ),
    ]
